/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkshopRouteImport } from './routes/workshop'
import { Route as TournamentsRouteImport } from './routes/tournaments'
import { Route as ThemesRouteImport } from './routes/themes'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as MyLibraryRouteImport } from './routes/my-library'
import { Route as MyChartsRouteImport } from './routes/my-charts'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HistoricalBuilderRouteImport } from './routes/historical-builder'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as CreateAccountRouteImport } from './routes/create-account'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TournamentsTournamentIdRouteImport } from './routes/tournaments.$tournamentId'
import { Route as EditorPrintRouteImport } from './routes/editor.print'
import { Route as EditorNewRouteImport } from './routes/editor.new'
import { Route as EditorChartIdRouteImport } from './routes/editor.$chartId'
import { Route as CheckoutSuccessRouteImport } from './routes/checkout.success'
import { Route as CheckoutCancelledRouteImport } from './routes/checkout.cancelled'
import { Route as AdminSecurityLogsRouteImport } from './routes/admin.security-logs'
import { Route as AdminAiLogsRouteImport } from './routes/admin.ai-logs'
import { Route as TournamentsTournamentIdSeasonIdRouteImport } from './routes/tournaments.$tournamentId.$seasonId'
import { Route as EditorChartIdPrintRouteImport } from './routes/editor.$chartId.print'
import { Route as EditorChartIdBackgroundRouteImport } from './routes/editor.$chartId.background'

const WorkshopRoute = WorkshopRouteImport.update({
  id: '/workshop',
  path: '/workshop',
  getParentRoute: () => rootRouteImport,
} as any)
const TournamentsRoute = TournamentsRouteImport.update({
  id: '/tournaments',
  path: '/tournaments',
  getParentRoute: () => rootRouteImport,
} as any)
const ThemesRoute = ThemesRouteImport.update({
  id: '/themes',
  path: '/themes',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const MyLibraryRoute = MyLibraryRouteImport.update({
  id: '/my-library',
  path: '/my-library',
  getParentRoute: () => rootRouteImport,
} as any)
const MyChartsRoute = MyChartsRouteImport.update({
  id: '/my-charts',
  path: '/my-charts',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoricalBuilderRoute = HistoricalBuilderRouteImport.update({
  id: '/historical-builder',
  path: '/historical-builder',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateAccountRoute = CreateAccountRouteImport.update({
  id: '/create-account',
  path: '/create-account',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TournamentsTournamentIdRoute = TournamentsTournamentIdRouteImport.update({
  id: '/$tournamentId',
  path: '/$tournamentId',
  getParentRoute: () => TournamentsRoute,
} as any)
const EditorPrintRoute = EditorPrintRouteImport.update({
  id: '/editor/print',
  path: '/editor/print',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorNewRoute = EditorNewRouteImport.update({
  id: '/editor/new',
  path: '/editor/new',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorChartIdRoute = EditorChartIdRouteImport.update({
  id: '/editor/$chartId',
  path: '/editor/$chartId',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutSuccessRoute = CheckoutSuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => CheckoutRoute,
} as any)
const CheckoutCancelledRoute = CheckoutCancelledRouteImport.update({
  id: '/cancelled',
  path: '/cancelled',
  getParentRoute: () => CheckoutRoute,
} as any)
const AdminSecurityLogsRoute = AdminSecurityLogsRouteImport.update({
  id: '/security-logs',
  path: '/security-logs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAiLogsRoute = AdminAiLogsRouteImport.update({
  id: '/ai-logs',
  path: '/ai-logs',
  getParentRoute: () => AdminRoute,
} as any)
const TournamentsTournamentIdSeasonIdRoute =
  TournamentsTournamentIdSeasonIdRouteImport.update({
    id: '/$seasonId',
    path: '/$seasonId',
    getParentRoute: () => TournamentsTournamentIdRoute,
  } as any)
const EditorChartIdPrintRoute = EditorChartIdPrintRouteImport.update({
  id: '/print',
  path: '/print',
  getParentRoute: () => EditorChartIdRoute,
} as any)
const EditorChartIdBackgroundRoute = EditorChartIdBackgroundRouteImport.update({
  id: '/background',
  path: '/background',
  getParentRoute: () => EditorChartIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRouteWithChildren
  '/checkout': typeof CheckoutRouteWithChildren
  '/create-account': typeof CreateAccountRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/historical-builder': typeof HistoricalBuilderRoute
  '/login': typeof LoginRoute
  '/my-charts': typeof MyChartsRoute
  '/my-library': typeof MyLibraryRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/themes': typeof ThemesRoute
  '/tournaments': typeof TournamentsRouteWithChildren
  '/workshop': typeof WorkshopRoute
  '/admin/ai-logs': typeof AdminAiLogsRoute
  '/admin/security-logs': typeof AdminSecurityLogsRoute
  '/checkout/cancelled': typeof CheckoutCancelledRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/editor/$chartId': typeof EditorChartIdRouteWithChildren
  '/editor/new': typeof EditorNewRoute
  '/editor/print': typeof EditorPrintRoute
  '/tournaments/$tournamentId': typeof TournamentsTournamentIdRouteWithChildren
  '/editor/$chartId/background': typeof EditorChartIdBackgroundRoute
  '/editor/$chartId/print': typeof EditorChartIdPrintRoute
  '/tournaments/$tournamentId/$seasonId': typeof TournamentsTournamentIdSeasonIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRouteWithChildren
  '/checkout': typeof CheckoutRouteWithChildren
  '/create-account': typeof CreateAccountRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/historical-builder': typeof HistoricalBuilderRoute
  '/login': typeof LoginRoute
  '/my-charts': typeof MyChartsRoute
  '/my-library': typeof MyLibraryRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/themes': typeof ThemesRoute
  '/tournaments': typeof TournamentsRouteWithChildren
  '/workshop': typeof WorkshopRoute
  '/admin/ai-logs': typeof AdminAiLogsRoute
  '/admin/security-logs': typeof AdminSecurityLogsRoute
  '/checkout/cancelled': typeof CheckoutCancelledRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/editor/$chartId': typeof EditorChartIdRouteWithChildren
  '/editor/new': typeof EditorNewRoute
  '/editor/print': typeof EditorPrintRoute
  '/tournaments/$tournamentId': typeof TournamentsTournamentIdRouteWithChildren
  '/editor/$chartId/background': typeof EditorChartIdBackgroundRoute
  '/editor/$chartId/print': typeof EditorChartIdPrintRoute
  '/tournaments/$tournamentId/$seasonId': typeof TournamentsTournamentIdSeasonIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRouteWithChildren
  '/checkout': typeof CheckoutRouteWithChildren
  '/create-account': typeof CreateAccountRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/historical-builder': typeof HistoricalBuilderRoute
  '/login': typeof LoginRoute
  '/my-charts': typeof MyChartsRoute
  '/my-library': typeof MyLibraryRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/themes': typeof ThemesRoute
  '/tournaments': typeof TournamentsRouteWithChildren
  '/workshop': typeof WorkshopRoute
  '/admin/ai-logs': typeof AdminAiLogsRoute
  '/admin/security-logs': typeof AdminSecurityLogsRoute
  '/checkout/cancelled': typeof CheckoutCancelledRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/editor/$chartId': typeof EditorChartIdRouteWithChildren
  '/editor/new': typeof EditorNewRoute
  '/editor/print': typeof EditorPrintRoute
  '/tournaments/$tournamentId': typeof TournamentsTournamentIdRouteWithChildren
  '/editor/$chartId/background': typeof EditorChartIdBackgroundRoute
  '/editor/$chartId/print': typeof EditorChartIdPrintRoute
  '/tournaments/$tournamentId/$seasonId': typeof TournamentsTournamentIdSeasonIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/admin'
    | '/checkout'
    | '/create-account'
    | '/forgot-password'
    | '/historical-builder'
    | '/login'
    | '/my-charts'
    | '/my-library'
    | '/pricing'
    | '/privacy'
    | '/reset-password'
    | '/terms'
    | '/themes'
    | '/tournaments'
    | '/workshop'
    | '/admin/ai-logs'
    | '/admin/security-logs'
    | '/checkout/cancelled'
    | '/checkout/success'
    | '/editor/$chartId'
    | '/editor/new'
    | '/editor/print'
    | '/tournaments/$tournamentId'
    | '/editor/$chartId/background'
    | '/editor/$chartId/print'
    | '/tournaments/$tournamentId/$seasonId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/admin'
    | '/checkout'
    | '/create-account'
    | '/forgot-password'
    | '/historical-builder'
    | '/login'
    | '/my-charts'
    | '/my-library'
    | '/pricing'
    | '/privacy'
    | '/reset-password'
    | '/terms'
    | '/themes'
    | '/tournaments'
    | '/workshop'
    | '/admin/ai-logs'
    | '/admin/security-logs'
    | '/checkout/cancelled'
    | '/checkout/success'
    | '/editor/$chartId'
    | '/editor/new'
    | '/editor/print'
    | '/tournaments/$tournamentId'
    | '/editor/$chartId/background'
    | '/editor/$chartId/print'
    | '/tournaments/$tournamentId/$seasonId'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/admin'
    | '/checkout'
    | '/create-account'
    | '/forgot-password'
    | '/historical-builder'
    | '/login'
    | '/my-charts'
    | '/my-library'
    | '/pricing'
    | '/privacy'
    | '/reset-password'
    | '/terms'
    | '/themes'
    | '/tournaments'
    | '/workshop'
    | '/admin/ai-logs'
    | '/admin/security-logs'
    | '/checkout/cancelled'
    | '/checkout/success'
    | '/editor/$chartId'
    | '/editor/new'
    | '/editor/print'
    | '/tournaments/$tournamentId'
    | '/editor/$chartId/background'
    | '/editor/$chartId/print'
    | '/tournaments/$tournamentId/$seasonId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  AdminRoute: typeof AdminRouteWithChildren
  CheckoutRoute: typeof CheckoutRouteWithChildren
  CreateAccountRoute: typeof CreateAccountRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  HistoricalBuilderRoute: typeof HistoricalBuilderRoute
  LoginRoute: typeof LoginRoute
  MyChartsRoute: typeof MyChartsRoute
  MyLibraryRoute: typeof MyLibraryRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  TermsRoute: typeof TermsRoute
  ThemesRoute: typeof ThemesRoute
  TournamentsRoute: typeof TournamentsRouteWithChildren
  WorkshopRoute: typeof WorkshopRoute
  EditorChartIdRoute: typeof EditorChartIdRouteWithChildren
  EditorNewRoute: typeof EditorNewRoute
  EditorPrintRoute: typeof EditorPrintRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workshop': {
      id: '/workshop'
      path: '/workshop'
      fullPath: '/workshop'
      preLoaderRoute: typeof WorkshopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tournaments': {
      id: '/tournaments'
      path: '/tournaments'
      fullPath: '/tournaments'
      preLoaderRoute: typeof TournamentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/themes': {
      id: '/themes'
      path: '/themes'
      fullPath: '/themes'
      preLoaderRoute: typeof ThemesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-library': {
      id: '/my-library'
      path: '/my-library'
      fullPath: '/my-library'
      preLoaderRoute: typeof MyLibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-charts': {
      id: '/my-charts'
      path: '/my-charts'
      fullPath: '/my-charts'
      preLoaderRoute: typeof MyChartsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historical-builder': {
      id: '/historical-builder'
      path: '/historical-builder'
      fullPath: '/historical-builder'
      preLoaderRoute: typeof HistoricalBuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create-account': {
      id: '/create-account'
      path: '/create-account'
      fullPath: '/create-account'
      preLoaderRoute: typeof CreateAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tournaments/$tournamentId': {
      id: '/tournaments/$tournamentId'
      path: '/$tournamentId'
      fullPath: '/tournaments/$tournamentId'
      preLoaderRoute: typeof TournamentsTournamentIdRouteImport
      parentRoute: typeof TournamentsRoute
    }
    '/editor/print': {
      id: '/editor/print'
      path: '/editor/print'
      fullPath: '/editor/print'
      preLoaderRoute: typeof EditorPrintRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editor/new': {
      id: '/editor/new'
      path: '/editor/new'
      fullPath: '/editor/new'
      preLoaderRoute: typeof EditorNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editor/$chartId': {
      id: '/editor/$chartId'
      path: '/editor/$chartId'
      fullPath: '/editor/$chartId'
      preLoaderRoute: typeof EditorChartIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/success': {
      id: '/checkout/success'
      path: '/success'
      fullPath: '/checkout/success'
      preLoaderRoute: typeof CheckoutSuccessRouteImport
      parentRoute: typeof CheckoutRoute
    }
    '/checkout/cancelled': {
      id: '/checkout/cancelled'
      path: '/cancelled'
      fullPath: '/checkout/cancelled'
      preLoaderRoute: typeof CheckoutCancelledRouteImport
      parentRoute: typeof CheckoutRoute
    }
    '/admin/security-logs': {
      id: '/admin/security-logs'
      path: '/security-logs'
      fullPath: '/admin/security-logs'
      preLoaderRoute: typeof AdminSecurityLogsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/ai-logs': {
      id: '/admin/ai-logs'
      path: '/ai-logs'
      fullPath: '/admin/ai-logs'
      preLoaderRoute: typeof AdminAiLogsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/tournaments/$tournamentId/$seasonId': {
      id: '/tournaments/$tournamentId/$seasonId'
      path: '/$seasonId'
      fullPath: '/tournaments/$tournamentId/$seasonId'
      preLoaderRoute: typeof TournamentsTournamentIdSeasonIdRouteImport
      parentRoute: typeof TournamentsTournamentIdRoute
    }
    '/editor/$chartId/print': {
      id: '/editor/$chartId/print'
      path: '/print'
      fullPath: '/editor/$chartId/print'
      preLoaderRoute: typeof EditorChartIdPrintRouteImport
      parentRoute: typeof EditorChartIdRoute
    }
    '/editor/$chartId/background': {
      id: '/editor/$chartId/background'
      path: '/background'
      fullPath: '/editor/$chartId/background'
      preLoaderRoute: typeof EditorChartIdBackgroundRouteImport
      parentRoute: typeof EditorChartIdRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAiLogsRoute: typeof AdminAiLogsRoute
  AdminSecurityLogsRoute: typeof AdminSecurityLogsRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAiLogsRoute: AdminAiLogsRoute,
  AdminSecurityLogsRoute: AdminSecurityLogsRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface CheckoutRouteChildren {
  CheckoutCancelledRoute: typeof CheckoutCancelledRoute
  CheckoutSuccessRoute: typeof CheckoutSuccessRoute
}

const CheckoutRouteChildren: CheckoutRouteChildren = {
  CheckoutCancelledRoute: CheckoutCancelledRoute,
  CheckoutSuccessRoute: CheckoutSuccessRoute,
}

const CheckoutRouteWithChildren = CheckoutRoute._addFileChildren(
  CheckoutRouteChildren,
)

interface TournamentsTournamentIdRouteChildren {
  TournamentsTournamentIdSeasonIdRoute: typeof TournamentsTournamentIdSeasonIdRoute
}

const TournamentsTournamentIdRouteChildren: TournamentsTournamentIdRouteChildren =
  {
    TournamentsTournamentIdSeasonIdRoute: TournamentsTournamentIdSeasonIdRoute,
  }

const TournamentsTournamentIdRouteWithChildren =
  TournamentsTournamentIdRoute._addFileChildren(
    TournamentsTournamentIdRouteChildren,
  )

interface TournamentsRouteChildren {
  TournamentsTournamentIdRoute: typeof TournamentsTournamentIdRouteWithChildren
}

const TournamentsRouteChildren: TournamentsRouteChildren = {
  TournamentsTournamentIdRoute: TournamentsTournamentIdRouteWithChildren,
}

const TournamentsRouteWithChildren = TournamentsRoute._addFileChildren(
  TournamentsRouteChildren,
)

interface EditorChartIdRouteChildren {
  EditorChartIdBackgroundRoute: typeof EditorChartIdBackgroundRoute
  EditorChartIdPrintRoute: typeof EditorChartIdPrintRoute
}

const EditorChartIdRouteChildren: EditorChartIdRouteChildren = {
  EditorChartIdBackgroundRoute: EditorChartIdBackgroundRoute,
  EditorChartIdPrintRoute: EditorChartIdPrintRoute,
}

const EditorChartIdRouteWithChildren = EditorChartIdRoute._addFileChildren(
  EditorChartIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  AdminRoute: AdminRouteWithChildren,
  CheckoutRoute: CheckoutRouteWithChildren,
  CreateAccountRoute: CreateAccountRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  HistoricalBuilderRoute: HistoricalBuilderRoute,
  LoginRoute: LoginRoute,
  MyChartsRoute: MyChartsRoute,
  MyLibraryRoute: MyLibraryRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  TermsRoute: TermsRoute,
  ThemesRoute: ThemesRoute,
  TournamentsRoute: TournamentsRouteWithChildren,
  WorkshopRoute: WorkshopRoute,
  EditorChartIdRoute: EditorChartIdRouteWithChildren,
  EditorNewRoute: EditorNewRoute,
  EditorPrintRoute: EditorPrintRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
